title:              Minyoung Jeong
email:              jeongmin0812@gmail.com
description:        Minyoung Jeong's page
author:             Minyoung Jeong
baseurl:            ""
url:                "https://minyoungjeong0812.github.io"

background_color: '#000'

# Social Profiles
twitter_username:   ""
github_username:    minyoungjeong0812
facebook_username:  ""
linkedin_username:  minyoung-jeong-2a66957b

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           7
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
